// frontend/src/app/components/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { 
  Home, 
  GamepadIcon, 
  Upload, 
  Trophy,
  LucideAngularModule
} from 'lucide-angular';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  template: `
    <div class="min-h-screen bg-background">
      <nav class="border-b border-border/50 bg-card/30 backdrop-blur-xl sticky top-0 z-50 shadow-lg shadow-black/5">
        <div class="container mx-auto px-4">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center gap-3 group cursor-pointer">
              <div class="flex h-10 w-10 items-center justify-center rounded-xl gradient-primary shadow-glow transition-all duration-300 group-hover:scale-110 group-hover:rotate-6 animate-float">
                <span class="text-xl font-bold text-primary-foreground">♔</span>
              </div>
              <span class="text-xl font-bold text-gradient">ChessPulse</span>
            </div>
            
            <div class="flex gap-1">
              <ng-container *ngFor="let item of navItems">
                <a 
                  [routerLink]="item.path"
                  routerLinkActive="bg-primary/10 text-primary border border-primary/20 shadow-md"
                  [routerLinkActiveOptions]="{exact: item.path === '/'}"
                  class="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all duration-200 text-muted-foreground hover:bg-muted/50 hover:text-foreground hover:-translate-y-0.5"
                >
                  <lucide-angular [img]="item.icon" class="h-4 w-4"></lucide-angular>
                  {{ item.label }}
                </a>
              </ng-container>
            </div>
          </div>
        </div>
      </nav>
      
      <main class="container mx-auto px-4 py-8">
        <ng-content></ng-content>
      </main>
    </div>
  `
})
export class LayoutComponent {
  navItems = [
    { path: '/', label: 'Dashboard', icon: Home },
    { path: '/games', label: 'Games', icon: GamepadIcon },
    { path: '/upload', label: 'Upload', icon: Upload },
    { path: '/tournaments', label: 'Tournaments', icon: Trophy }
  ];

  constructor(private router: Router) {}
}

// frontend/src/components/Layout.tsx
import { Link, useLocation } from "react-router-dom";
import { BarChart3, Upload, Home, Trophy } from "lucide-react";
import { cn } from "@/lib/utils";

export const Layout = ({ children }: { children: React.ReactNode }) => {
  const location = useLocation();

  const navItems = [
    { path: "/", icon: Home, label: "Dashboard" },
    { path: "/upload", icon: Upload, label: "Upload" },
    { path: "/games", icon: BarChart3, label: "Games" },
    { path: "/tournaments", icon: Trophy, label: "Tournaments" },
  ];

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border bg-card">
        <div className="container mx-auto px-4">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
                <span className="text-xl font-bold text-primary-foreground">♔</span>
              </div>
              <span className="text-xl font-bold text-foreground">ChessPulse</span>
            </div>
            
            <div className="flex gap-1">
              {navItems.map((item) => {
                const Icon = item.icon;
                const isActive = location.pathname === item.path;
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={cn(
                      "flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors",
                      isActive
                        ? "bg-secondary text-secondary-foreground"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground"
                    )}
                  >
                    <Icon className="h-4 w-4" />
                    {item.label}
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </nav>
      
      <main className="container mx-auto px-4 py-8">
        {children}
      </main>
    </div>
  );
};
