// frontend/src/components/Layout.tsx
import { Link, useLocation } from "react-router-dom";
import { BarChart3, Upload, Home, Trophy } from "lucide-react";
import { cn } from "@/lib/utils";

export const Layout = ({ children }: { children: React.ReactNode }) => {
  const location = useLocation();

  const navItems = [
    { path: "/", icon: Home, label: "Dashboard" },
    { path: "/upload", icon: Upload, label: "Upload" },
    { path: "/games", icon: BarChart3, label: "Games" },
    { path: "/tournaments", icon: Trophy, label: "Tournaments" },
  ];

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border bg-card">
        <div className="container mx-auto px-4">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
                <span className="text-xl font-bold text-primary-foreground">♔</span>
              </div>
              <span className="text-xl font-bold text-foreground">ChessMind</span>
            </div>
            
            <div className="flex gap-1">
              {navItems.map((item) => {
                const Icon = item.icon;
                const isActive = location.pathname === item.path;
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={cn(
                      "flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors",
                      isActive
                        ? "bg-secondary text-secondary-foreground"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground"
                    )}
                  >
                    <Icon className="h-4 w-4" />
                    {item.label}
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </nav>
      
      <main className="container mx-auto px-4 py-8">
        {children}
      </main>
    </div>
  );
};

// frontend/chess-ui/src/app/components/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="min-h-screen bg-background">
      <nav class="border-b bg-card">
        <div class="container mx-auto px-4">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center gap-2">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
                <span class="text-xl text-primary-foreground">♔</span>
              </div>
              <span class="text-xl text-foreground">ChessMind</span>
            </div>
            
            <div class="flex gap-4">
              <a routerLink="/" routerLinkActive="bg-secondary text-secondary-foreground" 
                 class="flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground">
                🏠 Dashboard
              </a>
              <a routerLink="/upload" routerLinkActive="bg-secondary text-secondary-foreground"
                 class="flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground">
                📤 Upload
              </a>
              <a routerLink="/games" routerLinkActive="bg-secondary text-secondary-foreground"
                 class="flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground">
                📊 Games
              </a>
              <a routerLink="/tournaments" routerLinkActive="bg-secondary text-secondary-foreground"
                 class="flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground">
                🏆 Tournaments
              </a>
            </div>
          </div>
        </div>
      </nav>
      
      <main class="container mx-auto px-4 py-8">
        <ng-content></ng-content>
      </main>
    </div>
  `
})
export class LayoutComponent {}
